version: "3.0"

services:
  qr-code-service:
    image: pjanczyk/qr-code-generator_web
    ports:
      - "5700:5700"

  web:
    image: pjanczyk/qr-code-generator_qr-code-service
    ports:
      - "780:780"
    environment:
      QR_CODE_GENERATOR_BASE_URL: http://qrcode.piotrjanczyk.com
      QR_CODE_GENERATOR_QR_CODE_SERVICE_ADDRESS: qrcode.piotrjanczyk.com:5000
